default_config:

logger:
  default: info
  logs:
    custom_components.vrknock_client: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
